### ISSUE TITLE
Hard Nix dependency

### ISSUE THREAD

**Issue by spacefault** [gradetools/parliament-bomb#11]
The entire project at the moment assumes you have all of the dependencies through Nix. While this is good, and we should leave it as our main way of getting the project running, we should consider loosening the dependency to Nix. People may not be able to run Nix because of Nix's hard dependency on systemd. 

We should consider making some alternative installation / developer methods. The Nix installation method should be the main way of getting the project running, but we should also have some other methods aswell. We can mark these as "unsupported" if we feel like we don't have the time to maintain them that often.

This was discussed earlier, Please see #9

**Comment by caernarferon** [comment]
because the bot is (under my assumption) planned to be configured through a .toml file, it would be in theory, distro-agnostic. Should we create a branch for the experimental rewrite?

**Comment by caernarferon** [comment]
Additionally, as the project (parliamentd) relies on systemd even without Nix, it would be a waste of time and effort to extend support to non-systemd users.

**Comment by spacefault** [comment]
> because the bot is (under my assumption) planned to be configured through a .toml file, it would be in theory, distro-agnostic. Should we create a branch for the experimental rewrite?

Even though the server is configured through .toml, the current installation method requires Nix to download dependencies. We can have the users who do not wish to use Nix manually download & install all of the dependencies. We mostly need to edit the Makefile though, because it would not work on *nix, BSD, and other systems, and it would not work without GCC.

 > Additionally, as the project (parliamentd) relies on systemd even without Nix, it would be a waste of time and effort to extend support to non-systemd users.

This is only for timing, which we can do within parliamentctl or cron (for unofficial installations). We were able to drop the dependence for `journalctl` by getting rid of the `<systemd/sd-journal.h>` header file in `parliamentctl.c`, and just logging each run to  `$parliamentdir`. The extra components of `parliamentd` are designed to work with or without systemd.

If we need to, we can have systemd support as a compiler option, which can be used for optional systemd support.

**Comment by bolt926** [comment]
> Additionally, as the project (parliamentd) relies on systemd even without Nix, it would be a waste of time and effort to extend support to non-systemd users.


Currently, the project does not rely on systemd, and builds and runs on FreeBSD 14.0 without issue. From here, using systemd is an active decision that we can make.

**Comment by spacefault** [comment]
No longer relevant, ParliamentBomb can be compiled with Cargo, and Cargo should be installable on a bunch of systems. There are also no systemd dependencies at the moment.
